[[redirects]]
  from = "/"
  to = "/home"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/home"
  status = 200
[[redirects]]
  from = "/"
  to = "/home"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"
  status = 200